In [5]:
import numpy as np
import pandas as pd

In [75]:
#Database for area codes can be found here: http://www.nanpa.com/nanp1/npa_report.csv
#Excel file for database headings can be found here: http://www.nanpa.com/area_codes/AreaCodeDatabaseDefinitions.xls

#read in the the headings excel file for area code database
Area_Codes_heading = pd.read_excel('/home/calvin/Documents/PrivacyStar/data/AreaCodeDatabaseDefinitions.xls')

#only want the "Field name" column, which is our headings
Area_Codes_heading = Area_Codes_heading["Field Name"]

#assign the headings we got from the excel file to dataframe using the names parameter 
Area_Codes = pd.read_csv("/home/calvin/Documents/PrivacyStar/data/npa_report.csv", names=Area_Codes_heading)

#We need all the rows but columns NPA, Location, Country
#DataFrame.lock[rows, columns], ':' means that we want all the rows
Area_Codes = Area_Codes.loc[:,['NPA','Location', 'Country']]

#drops the first entry because its junk
Area_Codes.drop(labels=0, inplace=True)

Area_Codes.head(5)
print Area_Codes[Area_Codes.NPA == '203'];

   NPA Location Country
4  203       CT      US

In [7]:
Phone_Record = pd.read_csv("/home/calvin/Documents/PrivacyStar/data/PhoneNumberTransactionsSeptember.txt", delimiter = "\t",chunksize=100000)

In [139]:
External = pd.DataFrame()
User = pd.DataFrame()
for row in Phone_Record.itertuples():
    External = External.append(Area_Codes[Area_Codes.NPA == str(row[3])], ignore_index=True)
    User = User.append(Area_Codes[Area_Codes.NPA == str(row[6])], ignore_index=True)

chunk["ExternalState"] = External["Location"]
chunk["ExternalCountry"] = External["Country"]
chunk["UserState"] = User["Location"]
chunk["UserCountry"] = User["Country"]

In [140]:
Phone_Record.head(10)

,Id,TransactionTime,ExternalAreaCode,ExternalExchange,HashedExternaLPhoneNumber,UserAreaCode,UserExchange,HashedUserPhoneNumber,ExternalState,ExternalCountry,UserState,UserCountry
0,4354225,09/10/2015 02:01 PM,720,456,B000CDF1ED92C19A9D7510C48B24AEB74B514411,313,721,B901E442C82A1D60B9A247E5C2A8C867FFAED756,CO,US,MI,US
1,4354226,09/10/2015 02:01 PM,800,531,0D52AB3434818C41274FF18E0B8A231342BF0CBB,754,235,2AC8CC2B8EC0304EB5FF54FBB255049D7A570036,NANP AREA,NaN,FL,US
2,4354227,09/10/2015 02:01 PM,866,451,6FBD40F1458BE9A9E6BE3F1BBBC1620480D32AE9,804,255,2414D567FC8A9899906A97310E26C36CB127B57B,NANP AREA,NaN,VA,US
3,4354228,09/10/2015 02:01 PM,866,668,10E89E8146D525B2869E11C13B0703C825C69581,678,368,6C9695C3475479C601B8922DE9B38CAC05412973,NANP AREA,NaN,GA,US
4,4354229,09/10/2015 02:01 PM,571,302,AA6599EEA1734C364AA930FAC39A4A303B709473,703,371,BC63E9A3F996D79188A247127DE2DA4B9198A942,VA,US,VA,US
5,4354230,09/10/2015 02:01 PM,866,451,6FBD40F1458BE9A9E6BE3F1BBBC1620480D32AE9,804,255,2414D567FC8A9899906A97310E26C36CB127B57B,NANP AREA,NaN,VA,US
6,4354231,09/10/2015 02:00 PM,800,481,54A496692485261C53F0573394E619DE750E07EC,863,808,4BC22925F96A36F6F25E32815433BE9435449432,NANP AREA,NaN,FL,US
7,4354232,09/10/2015 02:01 PM,727,449,6E521BC09B535EDD3A28237B463FD8D05EB9EAED,813,351,5A4624D98D673FAA8C3EACFB8C42DD0405995303,FL,US,FL,US
8,4354233,09/10/2015 02:01 PM,585,386,41CF3FA1CDF92988507C2BF73B9DD42A658AF1A4,817,938,668F40C3707C5D30FCAB56D61D234799B01BE87A,NY,US,TX,US
9,4354234,09/10/2015 02:01 PM,727,449,6E521BC09B535EDD3A28237B463FD8D05EB9EAED,813,351,5A4624D98D673FAA8C3EACFB8C42DD0405995303,FL,US,FL,US