In [9]:
import numpy as np
import pandas as pd

In [10]:
#Database for area codes can be found here: http://www.nanpa.com/nanp1/npa_report.csv
#Excel file for database headings can be found here: http://www.nanpa.com/area_codes/AreaCodeDatabaseDefinitions.xls

#read in the the headings excel file for area code database
Area_Codes_heading = pd.read_excel('/home/calvin/Documents/PrivacyStar/data/AreaCodeDatabaseDefinitions.xls')

#only want the "Field name" column, which is our headings
Area_Codes_heading = Area_Codes_heading["Field Name"]

#assign the headings we got from the excel file to dataframe using the names parameter 
Area_Codes = pd.read_csv("/home/calvin/Documents/PrivacyStar/data/npa_report.csv", names=Area_Codes_heading)

#We need all the rows but columns NPA, Location, Country
#DataFrame.lock[rows, columns], ':' means that we want all the rows
Area_Codes = Area_Codes.loc[:,['NPA','Location', 'Country']]

#drops the first entry because its junk
Area_Codes.drop(labels=0, inplace=True)

Area_Codes.head(5)

   NPA  Location Country
1  200       NaN     NaN
2  201        NJ      US
3  202        DC      US
4  203        CT      US
5  204  MANITOBA  CANADA

In [11]:
Phone_Record = pd.read_csv("/home/calvin/Documents/PrivacyStar/data/PhoneNumberTransactionsSeptember.txt", delimiter = "\t")

In [27]:
External = pd.DataFrame()
User = pd.DataFrame()

#limit data size so local computer can handle it
Phone_Record = Phone_Record.head(1000)

#iterate through rows as tuples
for row in Phone_Record.itertuples():
    #construct two dataframes that contain (state, country) by crossreferencing NPA area codes and Phone_Record area codes
    External = External.append(Area_Codes[Area_Codes.NPA == str(row[3])], ignore_index=True)
    User = User.append(Area_Codes[Area_Codes.NPA == str(row[6])], ignore_index=True)

#Add four new columns to the Phone_Record Dataframe 
Phone_Record["ExternalState"] = External["Location"]
Phone_Record["ExternalCountry"] = External["Country"]
Phone_Record["UserState"] = User["Location"]
Phone_Record["UserCountry"] = User["Country"]

In [28]:
Phone_Record.head(20)

,Id,TransactionTime,ExternalAreaCode,ExternalExchange,HashedExternaLPhoneNumber,UserAreaCode,UserExchange,HashedUserPhoneNumber,ExternalState,ExternalCountry,UserState,UserCountry
0,4354225,09/10/2015 02:01 PM,720,456,B000CDF1ED92C19A9D7510C48B24AEB74B514411,313,721,B901E442C82A1D60B9A247E5C2A8C867FFAED756,CO,US,MI,US
1,4354226,09/10/2015 02:01 PM,800,531,0D52AB3434818C41274FF18E0B8A231342BF0CBB,754,235,2AC8CC2B8EC0304EB5FF54FBB255049D7A570036,NANP AREA,NaN,FL,US
2,4354227,09/10/2015 02:01 PM,866,451,6FBD40F1458BE9A9E6BE3F1BBBC1620480D32AE9,804,255,2414D567FC8A9899906A97310E26C36CB127B57B,NANP AREA,NaN,VA,US
3,4354228,09/10/2015 02:01 PM,866,668,10E89E8146D525B2869E11C13B0703C825C69581,678,368,6C9695C3475479C601B8922DE9B38CAC05412973,NANP AREA,NaN,GA,US
4,4354229,09/10/2015 02:01 PM,571,302,AA6599EEA1734C364AA930FAC39A4A303B709473,703,371,BC63E9A3F996D79188A247127DE2DA4B9198A942,VA,US,VA,US
5,4354230,09/10/2015 02:01 PM,866,451,6FBD40F1458BE9A9E6BE3F1BBBC1620480D32AE9,804,255,2414D567FC8A9899906A97310E26C36CB127B57B,NANP AREA,NaN,VA,US
6,4354231,09/10/2015 02:00 PM,800,481,54A496692485261C53F0573394E619DE750E07EC,863,808,4BC22925F96A36F6F25E32815433BE9435449432,NANP AREA,NaN,FL,US
7,4354232,09/10/2015 02:01 PM,727,449,6E521BC09B535EDD3A28237B463FD8D05EB9EAED,813,351,5A4624D98D673FAA8C3EACFB8C42DD0405995303,FL,US,FL,US
8,4354233,09/10/2015 02:01 PM,585,386,41CF3FA1CDF92988507C2BF73B9DD42A658AF1A4,817,938,668F40C3707C5D30FCAB56D61D234799B01BE87A,NY,US,TX,US
9,4354234,09/10/2015 02:01 PM,727,449,6E521BC09B535EDD3A28237B463FD8D05EB9EAED,813,351,5A4624D98D673FAA8C3EACFB8C42DD0405995303,FL,US,FL,US
10,4354235,09/10/2015 12:49 PM,201,204,3909C3C9F91E37D1D0348B238F03403056300FAF,772,209,CD26E4FBACA459DC0A9178E0335EA3D60007A36A,NJ,US,FL,US
11,4354236,09/10/2015 12:49 PM,201,204,3909C3C9F91E37D1D0348B238F03403056300FAF,313,420,513ADED47B02A94E1C213F5C902D4F7E6CD61EB3,NJ,US,MI,US
12,4354237,09/10/2015 12:49 PM,678,666,93479F51CE811AF767D3090C22EE4937A5F07B83,404,437,CF63F645B3A9469743601532144E655C9210A99E,GA,US,GA,US
13,4354238,09/10/2015 02:02 PM,434,533,3BEAED03D9DA5F737715D5B0F689EB753752E255,215,839,DD17092B436DAA57F324060B8501E68486D2BCBD,VA,US,PA,US
14,4354239,09/10/2015 02:02 PM,313,483,6CB5BF0DC7E14AC6F1EA31B9D7F5AF74388885AB,313,463,A67BB20C18AB40B98C665774C0C68ED750FFB95C,MI,US,MI,US
15,4354240,09/10/2015 02:02 PM,708,916,1FA740F1C263533284DAF8F6015C43132241453A,708,692,6077CE5169D02125204D22363FE5E7979DDEBE41,IL,US,IL,US
16,4354241,09/10/2015 02:02 PM,800,410,4DFBC2C1DFCE41D0580F03328ED45ED077F76B31,908,422,0B8F1FDAD5054317795C2F870D72E162CFCA98EA,NANP AREA,NaN,NJ,US
17,4354242,09/10/2015 02:02 PM,800,410,4DFBC2C1DFCE41D0580F03328ED45ED077F76B31,908,422,0B8F1FDAD5054317795C2F870D72E162CFCA98EA,NANP AREA,NaN,NJ,US
18,4354243,09/10/2015 02:02 PM,800,572,1E1147B1CABB9187971D5122D6D3223B607D8D50,347,785,01DEE9B11FCD7E076E0822CCD9414E8AE1999431,NANP AREA,NaN,NY,US
19,4354244,09/10/2015 02:02 PM,407,513,98CC055889FD4D74D596F534FF9BD47E0105AD0F,407,860,32D626169FE14838B3A60E45235DD2F4008C7F8A,FL,US,FL,US